var bankData = [
    "Access Bank Plc",
    "Access Diamond",
    "United Bank of Africa",
    "Zenneth Bank Plc",
    "ECo Bank PLc",
    "Fertility Bank",
    "Mortgage Bank",
    "Jaiz bank",
    "Guarantee Trust Bank",
    "First Bank PLC",
    "Union Bank",
    "First city Monument Bank (FCMB)",
    "City Bank",
    "Sterling Bank",
    "Nirsal Microfinance Bank",
    "SunTrust Bank",
    "Heritage bank",
    "Wema Bank",
    "Keystone Bank",
    "Sky Bank",
    "Unity Bank PLc",
    "Polaris Bank",
    "Paycom (Opay)",
    "Carbon",
    "Palmpay",
    "9 Payment service Bank",
    "Stanbic IBTC Bank",
    "Kuda Microfinance Bank",
    "Moniepoint",
    "Globus Bank",
    "Provides Bank",
    "Paga",
    "Fairmoney Microfinance Bannk",
    "VDF microfince Bank"
];


export default bankData
